<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SanthoshN" failures="3" tests="8" name="Listeneres_demo_Testing_001" time="94.622" errors="0" timestamp="16 Feb 2025 10:25:23 GMT">
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTesWithInvalidData" time="3.909"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTesWithInvalidData" time="3.788"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTesWithInvalidData" time="4.099"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="4.532"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="4.516"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="13.607">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_001LoginTest.loginTestWithValidData(TC_001LoginTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="5.289">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_001LoginTest.loginTestWithValidData(TC_001LoginTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="4.953">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_001LoginTest.loginTestWithValidData(TC_001LoginTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
</testsuite> <!-- Listeneres_demo_Testing_001 -->
