<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SanthoshN" failures="3" tests="8" name="Listeneres_demo_Testing_002" time="91.872" errors="0" timestamp="16 Feb 2025 10:25:21 GMT">
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTesWithInvalidData" time="4.205"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTesWithInvalidData" time="4.094"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTesWithInvalidData" time="4.165"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.463"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.89"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="13.662">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_002_DashboardTest.loginTestWithValidData(TC_002_DashboardTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.918">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_002_DashboardTest.loginTestWithValidData(TC_002_DashboardTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="5.162">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_002_DashboardTest.loginTestWithValidData(TC_002_DashboardTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
</testsuite> <!-- Listeneres_demo_Testing_002 -->
