<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SanthoshN" failures="6" tests="16" name="Listeneres_demo_Testing_001_chrome" time="152.131" errors="0" timestamp="16 Feb 2025 11:24:26 GMT">
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTesWithInvalidData" time="3.987"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTesWithInvalidData" time="4.403"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTesWithInvalidData" time="3.889"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="4.121"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="4.473"/>
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="5.03">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_001LoginTest.loginTestWithValidData(TC_001LoginTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="4.789">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_001LoginTest.loginTestWithValidData(TC_001LoginTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_001LoginTest" name="loginTestWithValidData" time="5.03">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_001LoginTest.loginTestWithValidData(TC_001LoginTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTesWithInvalidData" time="4.096"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTesWithInvalidData" time="4.181"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTesWithInvalidData" time="4.022"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.057"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.114"/>
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.846">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_002_DashboardTest.loginTestWithValidData(TC_002_DashboardTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="4.984">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_002_DashboardTest.loginTestWithValidData(TC_002_DashboardTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
  <testcase classname="org.ee.test.TC_002_DashboardTest" name="loginTestWithValidData" time="5.41">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at org.ee.test.TC_002_DashboardTest.loginTestWithValidData(TC_002_DashboardTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTestWithValidData -->
</testsuite> <!-- Listeneres_demo_Testing_001_chrome -->
